//
// TnefCappedComplianceLogger.cs
//
// Author: Jeffrey Stedfast <jestedfa@microsoft.com>
//
// Copyright (c) 2013-2026 .NET Foundation and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

using System;

namespace MimeKit.Tnef {
	/// <summary>
	/// A TNEF compliance logger that limits how many times each violation may be reported.
	/// </summary>
	/// <remarks>
	/// <para>The number of issues a TNEF stream can produce is bounded only by its size, and the
	/// densest forms cost an attacker only a few bytes per issue, so an untrusted stream can be made
	/// to produce issues far faster than anything downstream can afford to record them.</para>
	/// <para>The budget is per violation rather than a single total, for the same reason as
	/// <see cref="CappedComplianceLogger"/>: a total budget would let a flood of cheap, harmless
	/// violations hide the interesting ones that follow it.</para>
	/// </remarks>
	sealed class TnefCappedComplianceLogger : ITnefComplianceLogger
	{
		// Note: One counter per violation. The enum is a small, dense, zero-based range, so this is a
		// flat array indexed by the violation rather than a dictionary.
		readonly int[] counts;
		readonly ITnefComplianceLogger logger;
		readonly int limit;
		bool reportedTruncation;

		/// <summary>
		/// Initialize a new instance of the <see cref="TnefCappedComplianceLogger"/> class.
		/// </summary>
		/// <remarks>
		/// Creates a new capped TNEF compliance logger.
		/// </remarks>
		/// <param name="logger">The logger to forward issues to.</param>
		/// <param name="limit">The maximum number of times that each violation may be reported.</param>
		public TnefCappedComplianceLogger (ITnefComplianceLogger logger, int limit)
		{
			// Note: TooManyComplianceIssues is deliberately left out of the array. It is not a defect
			// in the stream and is generated by this class rather than by the reader, so it is never
			// counted against a budget and never suppressed. It sits outside the contiguous range of
			// defects, so it falls into the pass-through branch of Log() on its own.
			this.counts = new int[(int) TnefComplianceViolation.DataSizeLimitExceeded + 1];
			this.logger = logger;
			this.limit = limit;
		}

		/// <summary>
		/// Get the logger that issues are forwarded to.
		/// </summary>
		/// <remarks>
		/// Gets the logger that issues are forwarded to.
		/// </remarks>
		/// <value>The inner logger.</value>
		public ITnefComplianceLogger InnerLogger {
			get { return logger; }
		}

		/// <summary>
		/// Reset the budget.
		/// </summary>
		/// <remarks>
		/// Resets the budget so that every violation may be reported afresh.
		/// </remarks>
		public void Reset ()
		{
			Array.Clear (counts, 0, counts.Length);
			reportedTruncation = false;
		}

		/// <summary>
		/// Log a TNEF compliance violation.
		/// </summary>
		/// <remarks>
		/// Forwards the issue to the inner logger unless the violation has already been reported the
		/// maximum number of times.
		/// </remarks>
		/// <param name="issue">The TNEF compliance issue that was detected.</param>
		public void Log (in TnefComplianceIssue issue)
		{
			int index = (int) issue.Violation;

			if ((uint) index >= (uint) counts.Length) {
				logger.Log (issue);
				return;
			}

			if (counts[index] < limit) {
				counts[index]++;
				logger.Log (issue);
				return;
			}

			// Note: The report is incomplete from the first suppressed issue onward, so the marker is
			// emitted there and not repeated. Repeating it for every violation that later reaches its
			// own limit would reintroduce, in miniature, the flooding this class exists to prevent.
			if (!reportedTruncation) {
				reportedTruncation = true;

				logger.Log (new TnefComplianceIssue (TnefComplianceViolation.TooManyComplianceIssues, issue.StreamOffset, issue.Depth, issue.AttributeTag, issue.PropertyTag));
			}
		}
	}
}
