//
// RtfToHtml.cs
//
// Author: Jeffrey Stedfast <jestedfa@microsoft.com>
//
// Copyright (c) 2013-2026 .NET Foundation and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Globalization;
using System.Collections.Generic;

using MimeKit.Utils;

namespace MimeKit.Text {
	/// <summary>
	/// An RTF to HTML converter.
	/// </summary>
	/// <remarks>
	/// <para>Used to convert Rich Text Format (RTF) documents into HTML.</para>
	/// <para>The converter implements the subset of the Rich Text Format (RTF) Specification, version 1.9.1,
	/// that can be meaningfully represented in HTML: character sets and code pages, Unicode escapes,
	/// paragraphs and paragraph alignment, line breaks, tables, bold, italic, underline, strikethrough,
	/// superscript, subscript, font sizes, foreground and background colors, and <c>HYPERLINK</c> fields.
	/// Destinations that do not contain document text (such as pictures, embedded objects, style sheets and
	/// document properties) are skipped, as is hidden text. The attachment placeholders (<c>\objattph</c>) that
	/// Microsoft Outlook and Exchange write are reported to the <see cref="ObjectPlaceholderCallback"/>.</para>
	/// <para>RTF documents that encapsulate HTML (such as those generated by Microsoft Outlook and Exchange),
	/// as described by [MS-OXRTFEX], have their original HTML extracted rather than having the RTF rendering
	/// of that HTML converted back into HTML. See <see cref="ExtractEncapsulatedHtml"/>.</para>
	/// <para>The converter is designed to be resilient against hostile input. Its memory usage does not depend
	/// on the size of the input: font table, color table and group nesting resources are bounded by
	/// <see cref="MaxFontTableEntries"/>, <see cref="MaxColorTableEntries"/> and <see cref="MaxGroupDepth"/>,
	/// embedded binary data (<c>\binN</c>) is skipped without being buffered, and only hyperlinks with
	/// <c>http</c>, <c>https</c>, <c>mailto</c>, <c>ftp</c> or <c>tel</c> URL schemes are rendered as links.</para>
	/// <note type="note">Since RTF is a 7-bit format in which non-ASCII characters are escaped, the
	/// <see cref="TextConverter.InputEncoding"/> defaults to ISO-8859-1 so that every byte of the input
	/// maps to exactly one character. The code page used to decode escaped characters is determined by the
	/// document itself (<c>\ansicpg</c>, <c>\fcharset</c> and <c>\cpg</c>).</note>
	/// <note type="security">
	/// <para>Encapsulated HTML is extracted as-is (subject to the <see cref="HtmlTagCallback"/>), exactly like
	/// <see cref="HtmlToHtml"/> would output it. <see cref="RtfToHtml"/> is not an HTML sanitizer. For
	/// displaying untrusted content, use a dedicated HTML sanitizer library.</para>
	/// </note>
	/// </remarks>
	public class RtfToHtml : TextConverter
	{
		int maxFontTableEntries = RtfToText.DefaultLimit;
		int maxColorTableEntries = RtfToText.DefaultLimit;
		int maxGroupDepth = RtfToText.DefaultLimit;
		int maxElementDepth = HtmlTokenizer.DefaultMaxElementDepth;
		HtmlNoScriptHandling noScriptHandling = HtmlNoScriptHandling.Unwrap;

		/// <summary>
		/// Initialize a new instance of the <see cref="RtfToHtml"/> class.
		/// </summary>
		/// <remarks>
		/// Creates a new RTF to HTML converter.
		/// </remarks>
		public RtfToHtml ()
		{
			InputEncoding = CharsetUtils.Latin1;
		}

		/// <summary>
		/// Get the input format.
		/// </summary>
		/// <remarks>
		/// Gets the input format.
		/// </remarks>
		/// <value>The input format.</value>
		public override TextFormat InputFormat {
			get { return TextFormat.RichText; }
		}

		/// <summary>
		/// Get the output format.
		/// </summary>
		/// <remarks>
		/// Gets the output format.
		/// </remarks>
		/// <value>The output format.</value>
		public override TextFormat OutputFormat {
			get { return TextFormat.Html; }
		}

		/// <summary>
		/// Get or set whether HTML encapsulated within the RTF should be extracted.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets whether HTML encapsulated within the RTF should be extracted.</para>
		/// <para>Microsoft Outlook and Exchange represent HTML message bodies as RTF documents that encapsulate
		/// the original HTML, as described by [MS-OXRTFEX]. Such documents declare themselves with the
		/// <c>\fromhtml1</c> control word. When this property is <see langword="true" />, the original HTML is
		/// extracted from those documents (as described by [MS-OXRTFEX] section 2.2.3.2) and passed through the
		/// <see cref="HtmlTagCallback"/>. When <see langword="false" />, or when the document does not encapsulate
		/// HTML, the RTF itself is converted into HTML.</para>
		/// </remarks>
		/// <value><see langword="true" /> if encapsulated HTML should be extracted; otherwise, <see langword="false" />.</value>
		public bool ExtractEncapsulatedHtml {
			get; set;
		} = true;

		/// <summary>
		/// Get or set the footer format.
		/// </summary>
		/// <remarks>
		/// Gets or sets the footer format.
		/// </remarks>
		/// <value>The footer format.</value>
		public HeaderFooterFormat FooterFormat {
			get; set;
		}

		/// <summary>
		/// Get or set the header format.
		/// </summary>
		/// <remarks>
		/// Gets or sets the header format.
		/// </remarks>
		/// <value>The header format.</value>
		public HeaderFooterFormat HeaderFormat {
			get; set;
		}

		/// <summary>
		/// Get or set the <see cref="HtmlTagCallback"/> method to use for custom
		/// filtering of HTML tags and content.
		/// </summary>
		/// <remarks>
		/// Get or set the <see cref="HtmlTagCallback"/> method to use for custom
		/// filtering of HTML tags and content.
		/// </remarks>
		/// <value>The html tag callback.</value>
		public HtmlTagCallback? HtmlTagCallback {
			get; set;
		}

		/// <summary>
		/// Get or set the <see cref="RtfHtmlObjectPlaceholderCallback"/> method to use for rendering attachment placeholders.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets the <see cref="RtfHtmlObjectPlaceholderCallback"/> method to use for rendering the
		/// attachment placeholders (<c>\objattph</c>) described by [MS-OXRTFEX] section 2.2.3.4.</para>
		/// <para>The callback is invoked once for each placeholder that is rendered, in document order. Placeholders
		/// that are hidden or that are within a destination that is skipped are not rendered. When the RTF encapsulates
		/// HTML and <see cref="ExtractEncapsulatedHtml"/> is <see langword="true" />, the placeholders are not rendered
		/// either, since the extracted HTML refers to its attachments by itself.</para>
		/// <para>When the value is <see langword="null" />, the placeholders are not rendered.</para>
		/// </remarks>
		/// <value>The object placeholder callback.</value>
		public RtfHtmlObjectPlaceholderCallback? ObjectPlaceholderCallback {
			get; set;
		}

		/// <summary>
		/// Get or set how <c>&lt;noscript&gt;</c> elements in encapsulated HTML should be handled.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets how <c>&lt;noscript&gt;</c> elements in HTML extracted from the RTF should be handled.</para>
		/// <para>This only applies when <see cref="ExtractEncapsulatedHtml"/> is <see langword="true" /> and the
		/// document encapsulates HTML. The HTML5 specification tokenizes the content of a <c>&lt;noscript&gt;</c>
		/// element differently depending on whether scripting is enabled in the application that renders the HTML
		/// (see <see cref="HtmlTokenizer.ScriptingEnabled"/>). When scripting is enabled, the content is raw text;
		/// when scripting is disabled, the content is normal markup.</para>
		/// <note type="security">
		/// <para>The encapsulated HTML is just as untrusted as any other HTML message body. If the
		/// <see cref="HtmlTagCallback"/> is being used to filter it (for example, to remove remote images or event
		/// handler attributes), then the output is only filtered correctly if the <c>&lt;noscript&gt;</c> content is
		/// tokenized the same way that the application that eventually renders the output will interpret it. A
		/// mismatch in either direction allows content to bypass the callback:</para>
		/// <list type="bullet">
		/// <item><description>When using <see cref="HtmlNoScriptHandling.ScriptingEnabled"/>, if the output is
		/// rendered with scripting disabled (as is typical for email clients), markup inside <c>&lt;noscript&gt;</c>
		/// elements, such as tracking images, remote content and forms, is never seen by the callback but
		/// <em>is</em> rendered.</description></item>
		/// <item><description>When using <see cref="HtmlNoScriptHandling.ScriptingDisabled"/>, if the output is
		/// rendered with scripting enabled, a <c>&lt;/noscript&gt;</c> hidden inside a comment or a raw text element
		/// such as <c>&lt;style&gt;</c> within a <c>&lt;noscript&gt;</c> element will close the
		/// <c>&lt;noscript&gt;</c> element in the renderer, allowing markup that the callback never saw
		/// (including script event handlers) to be rendered. This is a cross-site scripting (XSS)
		/// vulnerability.</description></item>
		/// </list>
		/// <para>The default value is <see cref="HtmlNoScriptHandling.Unwrap"/> (matching
		/// <see cref="HtmlToHtml.NoScriptHandling"/>), which tokenizes the content of <c>&lt;noscript&gt;</c>
		/// elements as normal markup (so that it is passed to the <see cref="HtmlTagCallback"/>) and removes the
		/// <c>&lt;noscript&gt;</c> start and end tags from the output. Since the output then contains no
		/// <c>&lt;noscript&gt;</c> elements, it is interpreted the same way regardless of whether scripting is enabled
		/// in the renderer. The trade-off is that the fallback content of <c>&lt;noscript&gt;</c> elements is always
		/// displayed, even by renderers that have scripting enabled.</para>
		/// <para>Note that <see cref="RtfToHtml"/> is not an HTML sanitizer. For displaying untrusted HTML,
		/// use a dedicated HTML sanitizer library.</para>
		/// </note>
		/// </remarks>
		/// <value>The method for handling <c>&lt;noscript&gt;</c> elements.</value>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <paramref name="value"/> is not a valid <see cref="HtmlNoScriptHandling"/> value.
		/// </exception>
		public HtmlNoScriptHandling NoScriptHandling {
			get { return noScriptHandling; }
			set {
				if (value < HtmlNoScriptHandling.Unwrap || value > HtmlNoScriptHandling.ScriptingDisabled)
					throw new ArgumentOutOfRangeException (nameof (value));

				noScriptHandling = value;
			}
		}

		/// <summary>
		/// Get or set whether the converter should only output an HTML fragment.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets whether the converter should only output an entire
		/// HTML document or just a fragment of the HTML body content.</para>
		/// <para>When extracting encapsulated HTML, the <c>&lt;!DOCTYPE&gt;</c>, <c>&lt;html&gt;</c>,
		/// <c>&lt;head&gt;</c> (including its content) and <c>&lt;body&gt;</c> tags are removed.</para>
		/// </remarks>
		/// <value><see langword="true" /> if the converter should only output an HTML fragment; otherwise, <see langword="false" />.</value>
		public bool OutputHtmlFragment {
			get; set;
		}

		/// <summary>
		/// Get or set the maximum number of font table entries.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets the maximum number of entries that will be recorded from the document's font table.</para>
		/// <para>Each font table entry may specify the character set used to decode text formatted with that font.
		/// Font table entries beyond this limit are ignored and text formatted with those fonts is decoded using
		/// the document's default code page.</para>
		/// </remarks>
		/// <value>The maximum number of font table entries.</value>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <paramref name="value"/> is less than <c>1</c>.
		/// </exception>
		public int MaxFontTableEntries {
			get { return maxFontTableEntries; }
			set { maxFontTableEntries = RtfToText.ValidateLimit (value); }
		}

		/// <summary>
		/// Get or set the maximum number of color table entries.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets the maximum number of entries that will be recorded from the document's color table.</para>
		/// <para>Color table entries beyond this limit are ignored and text that references them is rendered
		/// using the default color.</para>
		/// </remarks>
		/// <value>The maximum number of color table entries.</value>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <paramref name="value"/> is less than <c>1</c>.
		/// </exception>
		public int MaxColorTableEntries {
			get { return maxColorTableEntries; }
			set { maxColorTableEntries = RtfToText.ValidateLimit (value); }
		}

		/// <summary>
		/// Get or set the maximum group depth.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets the maximum number of distinct nested group states that will be tracked.</para>
		/// <para>RTF groups (<c>{</c> ... <c>}</c>) save and restore formatting state. Consecutive nested
		/// groups that do not change the state between them share a single entry, so arbitrarily deep nesting
		/// of groups that do not change any formatting does not count towards this limit. The content of any
		/// group that would exceed this limit is discarded.</para>
		/// </remarks>
		/// <value>The maximum group depth.</value>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <paramref name="value"/> is less than <c>1</c>.
		/// </exception>
		public int MaxGroupDepth {
			get { return maxGroupDepth; }
			set { maxGroupDepth = RtfToText.ValidateLimit (value); }
		}

		/// <summary>
		/// Get or set the maximum element depth of encapsulated HTML.
		/// </summary>
		/// <remarks>
		/// <para>Gets or sets the maximum number of distinct nested elements that will be tracked while
		/// tokenizing HTML extracted from the RTF (see <see cref="HtmlToHtml.MaxElementDepth"/>).</para>
		/// <para>This only applies when <see cref="ExtractEncapsulatedHtml"/> is <see langword="true" /> and the
		/// document encapsulates HTML. Consecutive nested elements that are identical share a single entry, so
		/// arbitrarily deep nesting of the same element does not count towards this limit. If a start tag exceeds
		/// this limit, then it is the last tag passed to the <see cref="HtmlTagCallback"/> and the remainder of the
		/// extracted HTML is written to the output as encoded text.</para>
		/// </remarks>
		/// <value>The maximum element depth.</value>
		/// <exception cref="System.ArgumentOutOfRangeException">
		/// <paramref name="value"/> is less than <c>1</c>.
		/// </exception>
		public int MaxElementDepth {
			get { return maxElementDepth; }
			set { maxElementDepth = RtfToText.ValidateLimit (value); }
		}

		class RtfToHtmlTagContext : HtmlTagContext
		{
			readonly HtmlAttributeCollection attrs;
			bool isEndTag;

			public RtfToHtmlTagContext (HtmlTagId tag, HtmlAttribute attr) : base (tag)
			{
				attrs = new HtmlAttributeCollection (new [] { attr });
			}

			public RtfToHtmlTagContext (HtmlTagId tag) : base (tag)
			{
				attrs = HtmlAttributeCollection.Empty;
			}

			public override string TagName {
				get { return TagId.ToHtmlTagName (); }
			}

			public override HtmlAttributeCollection Attributes {
				get { return attrs; }
			}

			public override bool IsEmptyElementTag {
				get { return TagId == HtmlTagId.Br; }
			}

			public override bool IsEndTag {
				get { return isEndTag; }
			}

			public void SetIsEndTag (bool value)
			{
				isEndTag = value;
			}
		}

		static void DefaultHtmlTagCallback (HtmlTagContext tagContext, HtmlWriter htmlWriter)
		{
			tagContext.WriteTag (htmlWriter, true);
		}

		static bool SuppressContent<T> (List<T> stack) where T : HtmlTagContext
		{
			for (int i = stack.Count; i > 0; i--) {
				if (stack[i - 1].SuppressInnerContent)
					return true;
			}

			return false;
		}

		void WriteHeader (TextWriter writer)
		{
			if (string.IsNullOrEmpty (Header))
				return;

			if (HeaderFormat == HeaderFooterFormat.Text) {
				var converter = new TextToHtml { OutputHtmlFragment = true };

				using (var sr = new StringReader (Header))
					converter.Convert (sr, writer);
			} else {
				writer.Write (Header);
			}
		}

		void WriteFooter (TextWriter writer)
		{
			if (string.IsNullOrEmpty (Footer))
				return;

			if (FooterFormat == HeaderFooterFormat.Text) {
				var converter = new TextToHtml { OutputHtmlFragment = true };

				using (var sr = new StringReader (Footer))
					converter.Convert (sr, writer);
			} else {
				writer.Write (Footer);
			}
		}

		enum ConversionMode
		{
			Undecided,
			Render,
			Extract
		}

		/// <summary>
		/// The character formatting that is rendered as a <c>&lt;span style="..."&gt;</c>.
		/// </summary>
		readonly struct SpanFormat : IEquatable<SpanFormat>
		{
			public const int DefaultFontSize = RtfInterpreter.DefaultFontSize;

			public readonly RtfStateFlags Flags;
			public readonly RtfVerticalAlignment VerticalAlignment;
			public readonly int FontSize;
			public readonly int Foreground;
			public readonly int Background;

			public SpanFormat (RtfInterpreter rtf)
			{
				ref readonly var state = ref rtf.State;

				Flags = state.Flags & (RtfStateFlags.Bold | RtfStateFlags.Italic | RtfStateFlags.Underline | RtfStateFlags.Strike);
				VerticalAlignment = state.VerticalAlignment;
				// A font size of 0 can only come from a malformed \fs0, which would make the text invisible.
				FontSize = state.FontSize > 0 ? state.FontSize : DefaultFontSize;

				// RTF 1.9.1, "Color Table": \cfN and \cbN are indexes into the color table. The first entry is
				// conventionally left empty to represent the automatic (default) color, and \cf0/\cb0 (which are
				// also the implicit defaults) are used by writers to mean "auto" even when that entry is defined,
				// so index 0, like an undefined entry, is rendered using the default color.
				Foreground = state.ForegroundColor > 0 ? rtf.GetColor (state.ForegroundColor) : -1;
				Background = state.BackgroundColor > 0 ? rtf.GetColor (state.BackgroundColor) : -1;
			}

			public bool IsDefault {
				get {
					return Flags == 0 && VerticalAlignment == RtfVerticalAlignment.Baseline && FontSize == DefaultFontSize &&
						Foreground == -1 && Background == -1;
				}
			}

			public bool Equals (SpanFormat other)
			{
				return Flags == other.Flags && VerticalAlignment == other.VerticalAlignment && FontSize == other.FontSize &&
					Foreground == other.Foreground && Background == other.Background;
			}

			public override bool Equals (object? obj)
			{
				return obj is SpanFormat other && Equals (other);
			}

			public override int GetHashCode ()
			{
				return ((int) Flags ^ ((int) VerticalAlignment << 8) ^ (FontSize << 12)) ^ Foreground ^ (Background * 31);
			}

			public string ToCss (StringBuilder builder)
			{
				builder.Clear ();

				if ((Flags & RtfStateFlags.Bold) != 0)
					builder.Append ("font-weight: bold; ");

				if ((Flags & RtfStateFlags.Italic) != 0)
					builder.Append ("font-style: italic; ");

				if ((Flags & (RtfStateFlags.Underline | RtfStateFlags.Strike)) != 0) {
					builder.Append ("text-decoration:");
					if ((Flags & RtfStateFlags.Underline) != 0)
						builder.Append (" underline");
					if ((Flags & RtfStateFlags.Strike) != 0)
						builder.Append (" line-through");
					builder.Append ("; ");
				}

				switch (VerticalAlignment) {
				case RtfVerticalAlignment.Superscript: builder.Append ("vertical-align: super; "); break;
				case RtfVerticalAlignment.Subscript: builder.Append ("vertical-align: sub; "); break;
				}

				if (FontSize != DefaultFontSize) {
					// Half-points to points.
					builder.Append ("font-size: ");
					builder.Append ((FontSize / 2).ToString (CultureInfo.InvariantCulture));
					if ((FontSize & 1) != 0)
						builder.Append (".5");
					builder.Append ("pt; ");
				}

				if (Foreground != -1)
					AppendColor (builder, "color: ", Foreground);

				if (Background != -1)
					AppendColor (builder, "background-color: ", Background);

				// Remove the trailing space.
				builder.Length--;

				return builder.ToString ();
			}

			static void AppendColor (StringBuilder builder, string property, int rgb)
			{
				builder.Append (property);
				builder.Append ('#');
				builder.Append (rgb.ToString ("X6", CultureInfo.InvariantCulture));
				builder.Append ("; ");
			}
		}

		/// <summary>
		/// Receives the content of the RTF document and either renders it as HTML or, for documents
		/// that encapsulate HTML, collects the extracted HTML so that <see cref="EncapsulatedHtmlReader"/>
		/// can feed it to an <see cref="HtmlTokenizer"/>.
		/// </summary>
		sealed class HtmlHandler : RtfContentHandler
		{
			static readonly char[] Tab = { '\u00A0', '\u00A0', '\u00A0', '\u00A0' };
			static readonly char[] Nbsp = { '\u00A0' };
			static readonly char[] CrLf = { '\r', '\n' };

			readonly List<RtfToHtmlTagContext> stack = new List<RtfToHtmlTagContext> ();
			readonly StringBuilder css = new StringBuilder ();

			// Documents typically reuse a small number of distinct character formats, so the CSS for each is
			// cached rather than rebuilt for every span. The cache is bounded (and simply cleared when full) so
			// that a document with many distinct formats cannot make it grow without limit.
			const int MaxCssCacheEntries = 256;
			readonly Dictionary<SpanFormat, string> cssCache = new Dictionary<SpanFormat, string> ();
			readonly HtmlTagCallback callback;
			readonly RtfHtmlObjectPlaceholderCallback? placeholderCallback;
			readonly RtfToHtml converter;
			readonly TextWriter output;
			HtmlWriter? htmlWriter;

			// Render mode state.
			SpanFormat spanFormat;
			string? href;
			int placeholderIndex;
			bool lastWasSpace;

			// Extract mode state: a queue of extracted HTML characters waiting to be read.
			char[] extracted = Array.Empty<char> ();
			int extractedIndex, extractedLength;

			public HtmlHandler (RtfToHtml converter, TextWriter output)
			{
				callback = converter.HtmlTagCallback ?? DefaultHtmlTagCallback;
				placeholderCallback = converter.ObjectPlaceholderCallback;
				this.converter = converter;
				this.output = output;
			}

			public ConversionMode Mode {
				get; private set;
			}

			public override void OnBegin (RtfInterpreter rtf)
			{
				// [MS-OXRTFEX] 2.2.3.1: by now, the recognition window has closed, so FromHtml is final.
				if (rtf.FromHtml && rtf.ExtractHtml) {
					Mode = ConversionMode.Extract;
					return;
				}

				// Make sure that \htmlrtf content is rendered and \htmltag destinations are skipped for the
				// remainder of the document, as an RTF reader that does not support de-encapsulation would.
				rtf.ExtractHtml = false;
				Mode = ConversionMode.Render;

				if (!converter.OutputHtmlFragment)
					output.Write ("<html><body>");

				converter.WriteHeader (output);

				htmlWriter = new HtmlWriter (output, true);
			}

			#region Extract mode

			void Append (char[] buffer, int index, int count)
			{
				if (extractedIndex == extractedLength) {
					extractedIndex = extractedLength = 0;
				} else if (extractedIndex > 0) {
					Buffer.BlockCopy (extracted, extractedIndex * 2, extracted, 0, (extractedLength - extractedIndex) * 2);
					extractedLength -= extractedIndex;
					extractedIndex = 0;
				}

				// The interpreter emits a bounded amount of content per Step(), and the reader drains the queue
				// before stepping again, so this buffer never grows beyond a small multiple of the token size.
				if (extractedLength + count > extracted.Length)
					Array.Resize (ref extracted, Math.Max (extractedLength + count, Math.Max (256, extracted.Length * 2)));

				Buffer.BlockCopy (buffer, index * 2, extracted, extractedLength * 2, count * 2);
				extractedLength += count;
			}

			public int ExtractedCount {
				get { return extractedLength - extractedIndex; }
			}

			public int ReadExtracted (char[] buffer, int index, int count)
			{
				int n = Math.Min (count, extractedLength - extractedIndex);

				Buffer.BlockCopy (extracted, extractedIndex * 2, buffer, index * 2, n * 2);
				extractedIndex += n;

				return n;
			}

			public void SkipExtracted ()
			{
				extractedIndex++;
			}

			public int PeekExtracted ()
			{
				return extractedIndex < extractedLength ? extracted[extractedIndex] : -1;
			}

			#endregion

			#region Render mode

			int IndexOf (HtmlTagId id)
			{
				for (int i = stack.Count - 1; i >= 0; i--) {
					if (stack[i].TagId == id)
						return i;
				}

				return -1;
			}

			void Open (RtfToHtmlTagContext ctx)
			{
				if (!SuppressContent (stack))
					callback (ctx, htmlWriter!);

				stack.Add (ctx);
			}

			void CloseTo (int count)
			{
				while (stack.Count > count) {
					var ctx = stack[stack.Count - 1];
					stack.RemoveAt (stack.Count - 1);

					if (ctx.TagId == HtmlTagId.A)
						href = null;

					if (SuppressContent (stack) || ctx.DeleteEndTag)
						continue;

					ctx.SetIsEndTag (true);

					if (ctx.InvokeCallbackForEndTag)
						callback (ctx, htmlWriter!);
					else
						ctx.WriteTag (htmlWriter!);

					if (ctx.TagId == HtmlTagId.Div || ctx.TagId == HtmlTagId.TR || ctx.TagId == HtmlTagId.Table)
						htmlWriter!.WriteMarkupText (Environment.NewLine);
				}
			}

			void Close (HtmlTagId id)
			{
				int index = IndexOf (id);

				if (index != -1)
					CloseTo (index);
			}

			void OpenTable ()
			{
				if (IndexOf (HtmlTagId.Table) == -1)
					Open (new RtfToHtmlTagContext (HtmlTagId.Table));

				if (IndexOf (HtmlTagId.TR) == -1)
					Open (new RtfToHtmlTagContext (HtmlTagId.TR));

				if (IndexOf (HtmlTagId.TD) == -1)
					Open (new RtfToHtmlTagContext (HtmlTagId.TD));
			}

			// Opens the block-level elements (table > tr > td > div) that the current content belongs in.
			void OpenBlock (RtfInterpreter rtf)
			{
				ref readonly var state = ref rtf.State;

				// RTF 1.9.1, "Table Definitions": paragraphs that belong to a table are marked with \intbl.
				// Since \pard resets \intbl, content that follows the last row of a table ends the table.
				if (state.InTable)
					OpenTable ();
				else
					Close (HtmlTagId.Table);

				if (IndexOf (HtmlTagId.Div) != -1)
					return;

				// RTF 1.9.1, "Paragraph Formatting Properties": \ql, \qc, \qr and \qj. Alignment is a paragraph
				// property, so the alignment in effect when the paragraph's first content is seen is used.
				var ctx = state.Alignment switch {
					RtfAlignment.Center => new RtfToHtmlTagContext (HtmlTagId.Div, new HtmlAttribute (HtmlAttributeId.Style, "text-align: center;")),
					RtfAlignment.Right => new RtfToHtmlTagContext (HtmlTagId.Div, new HtmlAttribute (HtmlAttributeId.Style, "text-align: right;")),
					RtfAlignment.Justify => new RtfToHtmlTagContext (HtmlTagId.Div, new HtmlAttribute (HtmlAttributeId.Style, "text-align: justify;")),
					_ => new RtfToHtmlTagContext (HtmlTagId.Div),
				};

				Open (ctx);
				lastWasSpace = true;
			}

			// Opens the inline elements (a > span) needed for the current character formatting, closing any
			// that no longer apply. Spans are never nested, so the depth of the output is bounded regardless
			// of how the RTF groups are nested.
			void OpenInline (RtfInterpreter rtf)
			{
				var link = rtf.State.Hyperlink;
				var format = new SpanFormat (rtf);
				int index;

				if ((index = IndexOf (HtmlTagId.A)) != -1 && !string.Equals (href, link, StringComparison.Ordinal))
					CloseTo (index);

				if ((index = IndexOf (HtmlTagId.Span)) != -1 && !format.Equals (spanFormat))
					CloseTo (index);

				if (link != null && IndexOf (HtmlTagId.A) == -1) {
					Open (new RtfToHtmlTagContext (HtmlTagId.A, new HtmlAttribute (HtmlAttributeId.Href, link)));
					href = link;
				}

				if (!format.IsDefault && IndexOf (HtmlTagId.Span) == -1) {
					Open (new RtfToHtmlTagContext (HtmlTagId.Span, new HtmlAttribute (HtmlAttributeId.Style, GetCss (format))));
					spanFormat = format;
				}
			}

			string GetCss (SpanFormat format)
			{
				if (!cssCache.TryGetValue (format, out var value)) {
					if (cssCache.Count >= MaxCssCacheEntries)
						cssCache.Clear ();

					value = format.ToCss (css);
					cssCache.Add (format, value);
				}

				return value;
			}

			// HTML collapses whitespace, but whitespace in RTF is significant. Runs of spaces are preserved
			// by alternating them with non-breaking spaces and tabs are approximated with non-breaking spaces.
			void WriteText (char[] buffer, int index, int count)
			{
				int endIndex = index + count;
				int startIndex = index;

				for (int i = index; i < endIndex; i++) {
					var c = buffer[i];

					if (c == ' ') {
						if (lastWasSpace) {
							htmlWriter!.WriteText (buffer, startIndex, i - startIndex);
							htmlWriter.WriteText (Nbsp, 0, 1);
							startIndex = i + 1;
							lastWasSpace = false;
						} else {
							lastWasSpace = true;
						}
					} else if (c == '\t') {
						htmlWriter!.WriteText (buffer, startIndex, i - startIndex);
						htmlWriter.WriteText (Tab, 0, Tab.Length);
						startIndex = i + 1;
						lastWasSpace = false;
					} else {
						lastWasSpace = false;
					}
				}

				if (startIndex < endIndex)
					htmlWriter!.WriteText (buffer, startIndex, endIndex - startIndex);
			}

			void WriteLineBreak ()
			{
				var ctx = new RtfToHtmlTagContext (HtmlTagId.Br);

				if (!SuppressContent (stack))
					callback (ctx, htmlWriter!);

				lastWasSpace = true;
			}

			public void Finish ()
			{
				CloseTo (0);
				htmlWriter!.Flush ();
				htmlWriter.Dispose ();
				htmlWriter = null;

				converter.WriteFooter (output);

				if (!converter.OutputHtmlFragment)
					output.Write ("</body></html>");
			}

			#endregion

			public override void OnText (RtfInterpreter rtf, char[] buffer, int index, int count)
			{
				if (Mode == ConversionMode.Extract) {
					// [MS-OXRTFEX] 2.2.3.2: text outside of \htmltag destinations (that is not suppressed by
					// \htmlrtf) is copied to the output; it is already HTML.
					Append (buffer, index, count);
					return;
				}

				OpenBlock (rtf);
				OpenInline (rtf);

				if (!SuppressContent (stack))
					WriteText (buffer, index, count);
			}

			public override void OnHtmlTag (RtfInterpreter rtf, char[] buffer, int index, int count)
			{
				// Only reported while de-encapsulating, i.e. in extract mode. [MS-OXRTFEX] 2.2.3.2: the content
				// of an HTMLTAG destination is copied to the output.
				if (Mode == ConversionMode.Extract)
					Append (buffer, index, count);
			}

			public override void OnParagraph (RtfInterpreter rtf)
			{
				if (Mode == ConversionMode.Extract) {
					// [MS-OXRTFEX] 2.2.3.2: \par is converted to CRLF.
					Append (CrLf, 0, 2);
					return;
				}

				// A paragraph with no content would be an empty <div> that browsers collapse, so give it a
				// line break to preserve the vertical space that the RTF paragraph occupies.
				bool empty = IndexOf (HtmlTagId.Div) == -1;

				OpenBlock (rtf);

				if (empty)
					WriteLineBreak ();

				Close (HtmlTagId.Div);
			}

			public override void OnLineBreak (RtfInterpreter rtf)
			{
				if (Mode == ConversionMode.Extract) {
					// [MS-OXRTFEX] 2.2.3.2: \line is converted to CRLF.
					Append (CrLf, 0, 2);
					return;
				}

				OpenBlock (rtf);
				OpenInline (rtf);
				WriteLineBreak ();
			}

			public override void OnCell (RtfInterpreter rtf)
			{
				if (Mode == ConversionMode.Extract)
					return;

				// RTF 1.9.1, "Table Definitions": \cell terminates a cell (which may be empty).
				OpenTable ();
				Close (HtmlTagId.TD);
			}

			public override void OnRow (RtfInterpreter rtf)
			{
				if (Mode == ConversionMode.Extract)
					return;

				// RTF 1.9.1, "Table Definitions": \row terminates a row.
				if (IndexOf (HtmlTagId.Table) == -1)
					Open (new RtfToHtmlTagContext (HtmlTagId.Table));

				if (IndexOf (HtmlTagId.TR) == -1)
					Open (new RtfToHtmlTagContext (HtmlTagId.TR));

				Close (HtmlTagId.TR);
			}

			public override void OnObjectPlaceholder (RtfInterpreter rtf)
			{
				// [MS-OXRTFEX] 2.2.3.4: the placeholders are only meaningful when the RTF itself is rendered. HTML
				// that is extracted from the RTF refers to its attachments by itself (e.g. using cid: URLs).
				if (Mode == ConversionMode.Extract)
					return;

				// The index is advanced even if the callback is not invoked so that the placeholders stay in lock
				// step with the attachment list.
				int index = placeholderIndex;

				if (placeholderIndex < int.MaxValue)
					placeholderIndex++;

				if (placeholderCallback is null)
					return;

				OpenBlock (rtf);
				OpenInline (rtf);

				if (!SuppressContent (stack))
					placeholderCallback (index, htmlWriter!);

				lastWasSpace = false;
			}
		}

		/// <summary>
		/// A <see cref="TextReader"/> that incrementally de-encapsulates HTML from an RTF document so that it
		/// can be streamed into an <see cref="HtmlTokenizer"/> without buffering the entire document.
		/// </summary>
		sealed class EncapsulatedHtmlReader : TextReader
		{
			readonly RtfInterpreter interpreter;
			readonly HtmlHandler handler;
			bool eof;

			public EncapsulatedHtmlReader (RtfInterpreter interpreter, HtmlHandler handler)
			{
				this.interpreter = interpreter;
				this.handler = handler;
			}

			bool Fill ()
			{
				while (handler.ExtractedCount == 0 && !eof)
					eof = !interpreter.Step ();

				return handler.ExtractedCount > 0;
			}

			public override int Peek ()
			{
				return Fill () ? handler.PeekExtracted () : -1;
			}

			public override int Read ()
			{
				int c = Peek ();

				if (c != -1)
					handler.SkipExtracted ();

				return c;
			}

			public override int Read (char[] buffer, int index, int count)
			{
				if (count == 0 || !Fill ())
					return 0;

				return handler.ReadExtracted (buffer, index, count);
			}
		}

		// The encapsulated HTML is just as untrusted as any other HTML, so it is filtered by the same logic as HtmlToHtml.
		void ConvertExtractedHtml (TextReader reader, TextWriter writer)
		{
			var converter = new HtmlToHtml {
				OutputHtmlFragment = OutputHtmlFragment,
				NoScriptHandling = NoScriptHandling,
				MaxElementDepth = maxElementDepth,
				HtmlTagCallback = HtmlTagCallback
			};

			WriteHeader (writer);
			converter.ConvertHtml (reader, writer);
			WriteFooter (writer);
		}

		/// <summary>
		/// Convert the contents of <paramref name="reader"/> from the <see cref="InputFormat"/> to the
		/// <see cref="OutputFormat"/> and uses the <paramref name="writer"/> to write the resulting text.
		/// </summary>
		/// <remarks>
		/// Converts the contents of <paramref name="reader"/> from the <see cref="InputFormat"/> to the
		/// <see cref="OutputFormat"/> and uses the <paramref name="writer"/> to write the resulting text.
		/// </remarks>
		/// <param name="reader">The text reader.</param>
		/// <param name="writer">The text writer.</param>
		/// <exception cref="System.ArgumentNullException">
		/// <para><paramref name="reader"/> is <see langword="null"/>.</para>
		/// <para>-or-</para>
		/// <para><paramref name="writer"/> is <see langword="null"/>.</para>
		/// </exception>
		public override void Convert (TextReader reader, TextWriter writer)
		{
			if (reader is null)
				throw new ArgumentNullException (nameof (reader));

			if (writer is null)
				throw new ArgumentNullException (nameof (writer));

			var handler = new HtmlHandler (this, writer);
			var interpreter = new RtfInterpreter (reader, handler, MaxGroupDepth, MaxFontTableEntries, MaxColorTableEntries) {
				ExtractHtml = ExtractEncapsulatedHtml
			};

			// [MS-OXRTFEX] 2.2.3.1: whether a document encapsulates HTML can only be determined after the first
			// few tokens have been read. The interpreter notifies the handler (via OnBegin) once that is known and
			// before any content is reported, at which point the handler decides how to convert the document.
			while (handler.Mode == ConversionMode.Undecided && interpreter.Step ())
				;

			if (handler.Mode == ConversionMode.Extract) {
				// Any content reported along with OnBegin has been queued by the handler and will be read first.
				using (var html = new EncapsulatedHtmlReader (interpreter, handler))
					ConvertExtractedHtml (html, writer);
			} else {
				while (interpreter.Step ())
					;

				handler.Finish ();
			}
		}

		/// <summary>
		/// Counts the attachment placeholders that <see cref="Convert(TextReader, TextWriter)"/> would report to the
		/// <see cref="ObjectPlaceholderCallback"/>.
		/// </summary>
		/// <remarks>
		/// [MS-OXRTFEX] 2.2.3.4: the placeholders are matched with the attachments only if their numbers are equal,
		/// which has to be known before the document is rendered.
		/// </remarks>
		/// <returns>The number of placeholders (saturating at <see cref="int.MaxValue"/>), or <c>-1</c> if the HTML
		/// encapsulated within the document would be extracted instead of rendering the RTF.</returns>
		internal int CountObjectPlaceholders (TextReader reader, CancellationToken cancellationToken)
		{
			var counter = new PlaceholderCounter ();
			var interpreter = new RtfInterpreter (reader, counter, MaxGroupDepth, MaxFontTableEntries, MaxColorTableEntries) {
				ExtractHtml = ExtractEncapsulatedHtml
			};

			while (!counter.Extract && interpreter.Step ())
				cancellationToken.ThrowIfCancellationRequested ();

			return counter.Extract ? -1 : counter.Count;
		}

		/// <summary>
		/// Determines whether <see cref="Convert(TextReader, TextWriter)"/> would extract the HTML encapsulated within
		/// the document rather than render the RTF.
		/// </summary>
		/// <remarks>
		/// Only the beginning of the document is normally read ([MS-OXRTFEX] 2.2.3.1).
		/// </remarks>
		/// <returns><see langword="true"/> if the encapsulated HTML would be extracted; otherwise, <see langword="false"/>.</returns>
		internal bool ExtractsEncapsulatedHtml (TextReader reader, CancellationToken cancellationToken)
		{
			var counter = new PlaceholderCounter ();
			var interpreter = new RtfInterpreter (reader, counter, MaxGroupDepth, MaxFontTableEntries, MaxColorTableEntries) {
				ExtractHtml = ExtractEncapsulatedHtml
			};

			while (!counter.Begun && interpreter.Step ())
				cancellationToken.ThrowIfCancellationRequested ();

			return counter.Extract;
		}

		internal sealed class PlaceholderCounter : RtfContentHandler
		{
			public bool Extract;
			public bool Begun;
			public int Count;

			public override void OnBegin (RtfInterpreter rtf)
			{
				Begun = true;

				// Mirrors HtmlHandler.OnBegin.
				if (rtf.FromHtml && rtf.ExtractHtml)
					Extract = true;
				else
					rtf.ExtractHtml = false;
			}

			public override void OnObjectPlaceholder (RtfInterpreter rtf)
			{
				if (Count < int.MaxValue)
					Count++;
			}
		}
	}
}
