From: develop@winews.net
Newsgroups: yenc
Date: 27 Oct 2001 15:07:44 +0200
Subject: yEnc-Prefix: "testfile.txt" 584 yEnc bytes - yEnc test (1)
Message-ID: <4407f.ra1200@liebchen.winews.net>
Path: liebchen.winews.net!not-for-mail
Lines: 16
X-Newsreader: MyNews

-- 
=ybegin line=128 size=584 name=testfile.txt 
£o˜JWJ~“–JR[S74k}mssdJ\__XXZ74)('&%$#"! =M=J=I=@ÿşıüûúùø÷öõôóòñğïîíìëêéèçæåäãâáàßŞİÜÛÚÙØ×ÖÕÔÓÒ
ÑĞÏÎÍÌËÊÉÈÇÆÅÄÃÂÁÀ¿¾½¼»º¹¸·¶µ´³²±°¯®­¬«ª©¨§¦¥¤£¢¡ Ÿœ›š™˜—–•”“’‘Œ‹Š‰ˆ‡†…„ƒ‚€~}|{zyxwvutsrqponmlkjihgfedcba`_^]\[ZYXWVUTSR
QPONMLKJIHGFEDCBA@?>=}<;:9876543210/=n-,+*74k}mssdJZXX\__74*+,-=n/0123456789:;<=}>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijkl
mnopqrstuvwxyz{|}~€‚ƒ„…†‡ˆ‰Š‹Œ‘’“”•–—˜™š›œŸ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏĞÑÒÓÔÕÖ×ØÙÚÛÜİŞßàáâãäåæçèéêëì
íîïğñòóôõö÷øùúûüışÿ=@=I=J=M !"#$%&'()74o˜J™J~“–74
=yend size=584 crc32=ded29f4f 
