Delivered-To: jeff@xamarin.com
Received: by 10.152.106.50 with SMTP id gr18csp137848lab;
        Wed, 28 May 2014 11:02:10 -0700 (PDT)
X-Received: by 10.69.15.2 with SMTP id fk2mr1356990pbd.123.1401300130069;
        Wed, 28 May 2014 11:02:10 -0700 (PDT)
Return-Path: <975-JOX-769.0.1923.0.0.2611.7.1928@em-sj-77.mktomail.com>
Received: from em-sj-82.mktomail.com (em-sj-82.mktomail.com. [199.15.215.82])
        by mx.google.com with ESMTP id bb9si24506648pbd.51.2014.05.28.11.02.09
        for <jeff@xamarin.com>;
        Wed, 28 May 2014 11:02:10 -0700 (PDT)
Received-SPF: pass (google.com: domain of 975-JOX-769.0.1923.0.0.2611.7.1928@em-sj-77.mktomail.com designates 199.15.215.82 as permitted sender) client-ip=199.15.215.82;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of 975-JOX-769.0.1923.0.0.2611.7.1928@em-sj-77.mktomail.com designates 199.15.215.82 as permitted sender) smtp.mail=975-JOX-769.0.1923.0.0.2611.7.1928@em-sj-77.mktomail.com;
       dkim=pass header.i=@xamarin.com
Return-Path: <newsletter@xamarin.com>
DKIM-Signature: v=1; a=rsa-sha256; d=xamarin.com; s=m1; c=relaxed/relaxed;
	q=dns/txt; i=@xamarin.com; t=1401300129;
	h=From:Subject:Date:To:MIME-Version:Content-Type;
	bh=+uPdX+4sXVSbt8FGX0BNY5EvnR8EeCiH2azw9tfNb4k=;
	b=WxF9umjPV1JISG57I0NUUqBP1PlhR7fjS2YhM1YbrvjjgEP2peDGXvu8ofmIpcpd
	0BBD2a+8jT7bGKeMSnlf2pJcTZn7TJlbaqlqSJMFgD9kxcpdQiH4LiskQMmOdwsx
	hCn0Ymyt9vlLQRbRW8rMUOBw1bjfX14eCMOrtbVzEyc=;
X-MSFBL: amVmZkB4YW1hcmluLmNvbUBkdnAtMTk5LTE1LTIxNS04MkBiZy1zai0wMUA5NzUt
	Sk9YLTc2OToyMjkxOjE5MjM6NDE2NjoyOjI2MTE6NzoxOTI4
Received: from [10.0.8.1] ([10.0.8.1:43344] helo=sjmas02.marketo.org)
	by sjmta06.marketo.org (envelope-from <newsletter@xamarin.com>)
	(ecelerity 3.5.0.35861 r(Momo-dev:tip)) with ESMTP
	id 87/33-62997-1A426835; Wed, 28 May 2014 13:02:09 -0500
Date: Wed, 28 May 2014 13:02:09 -0500 (CDT)
From: Xamarin <newsletter@xamarin.com>
Reply-To: newsletter@xamarin.com
To: jeff@xamarin.com
Message-ID: <1491930887.-1536873952.1401300129261.JavaMail.root@sjmas02.marketo.org>
Subject: Announcing Xamarin 3
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_-1536873954_1486546957.1401300129261"
X-Report-Abuse: Please report abuse here: http://www.marketo.com/policy
X-Binding: bg-sj-01
X-MarketoID: 975-JOX-769:2291:1923:4166:2:2611:7:1928
List-Unsubscribe: <mailto:KZ2W63BQL44UG2CCN5BGMYZYKBJGGURWGZIT2PI.1923.2611.7@unsub-sj.mktomail.com>
X-Mailfrom: 975-JOX-769.0.1923.0.0.2611.7.1928@em-sj-77.mktomail.com

------=_Part_-1536873954_1486546957.1401300129261
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&ut=
m_medium=3Demail&utm_content=3Dsay-hello&utm_campaign=3Dxamarin3>


Today we are very excited to announce Xamarin 3, which includes four major =
advances in mobile development:















 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dxamarin-designer-copy&utm_campaign=3Dxamari=
n3>






 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dxamarin-designer&utm_campaign=3Dxamarin3>


Xamarin is proud to unveil the world's best user interface designer for iOS=
, integrated into both Xamarin Studio and Visual Studio. Build beautiful na=
tive user interfaces, including live preview of custom controls, from the c=
omfort of your favorite IDE. Learn more =C2=BB <http://blog.xamarin.com/ann=
ouncing-xamarin-3/?utm_source=3Dannouncement&utm_medium=3Demail&utm_content=
=3Dxamarin-designer-learn-more&utm_campaign=3Dxamarin3>















 <http://xamarin.com/forms?utm_source=3Dannouncement&utm_medium=3Demail&utm=
_content=3Dxamarin-forms-copy&utm_campaign=3Dxamarin3>






 <http://xamarin.com/forms?utm_source=3Dannouncement&utm_medium=3Demail&utm=
_content=3Dxamarin-forms-image&utm_campaign=3Dxamarin3>


Xamarin.Forms is a simple API that allows developers to quickly and easily =
build native iOS, Android and Windows Phone user interfaces from a single, =
shared C# codebase. Delivered as a portable class library, Xamarin.Forms in=
cludes more than 40 controls and layouts and makes it easy to mix and match=
 your shared UI code with the native, platform-specific user interface capa=
bilities Xamarin has always given you. Learn more =C2=BB <http://xamarin.co=
m/forms?utm_source=3Dannouncement&utm_medium=3Demail&utm_content=3Dxamarin-=
forms-learn-more&utm_campaign=3Dxamarin3>















 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dsmooth-codesharing-copy&utm_campaign=3Dxama=
rin3>






 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dsmooth-codesharing-image&utm_campaign=3Dxam=
arin3>


Xamarin 3 introduces Shared Projects and full support for Portable Class Li=
braries =E2=80=94 two great new code-sharing techniques for cross-platform =
apps. Learn more =C2=BB <http://blog.xamarin.com/announcing-xamarin-3/?utm_=
source=3Dannouncement&utm_medium=3Demail&utm_content=3Dsmooth-codesharing-l=
earn-more&utm_campaign=3Dxamarin3>















 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dmajor-ide-copy&utm_campaign=3Dxamarin3>






 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dmajor-ide-image&utm_campaign=3Dxamarin3>


Xamarin now includes a major user experience refresh, support for NuGet pac=
kages, full .NET BCL documentation, source analysis, F# support, streamline=
d Visual Studio support, and many other great features. Learn more =C2=BB <=
http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&utm=
_medium=3Demail&utm_content=3Dmajor-ide-learn-more&utm_campaign=3Dxamarin3>















 <http://blog.xamarin.com/announcing-xamarin-3/?utm_source=3Dannouncement&u=
tm_medium=3Demail&utm_content=3Dmuch-more-copy&utm_campaign=3Dxamarin3>






These are just four of the hundreds of new features and enhancements in Xam=
arin 3. Please join us at one of two live webinars this Friday, May 30, <ht=
tp://blog.xamarin.com/announcing-xamarin-3/> where Xamarin co-founders Nat =
Friedman and Miguel de Icaza will present an overview of Xamarin 3. All web=
inar registrants will receive a copy of the recording, so please feel free =
to register even if you can't attend.














 <http://resources.xamarin.com/say-hello-to-xamarin-3-5am.html?utm_source=
=3Dannouncement&utm_medium=3Demail&utm_content=3Dregister-5am&utm_campaign=
=3Dxamarin3>








 <http://resources.xamarin.com/say-hello-to-xamarin-3-11am.html?utm_source=
=3Dannouncement&utm_medium=3Demail&utm_content=3Dregister-11am&utm_campaign=
=3Dxamarin3>










We've spent countless hours ensuring that Xamarin 3 is our best release yet=
, and we can't wait to show you what we've done.



















 <http://www.xamarin.com>
 <http://blog.xamarin.com/>
 <http://www.linkedin.com/company/xamarin>
 <https://www.facebook.com/xamarinhq>
 <https://plus.google.com/101300081691995092351>
 <https://twitter.com/xamarinhq>














=C2=A0=C2=A0394 Pacific Ave. 4th Floor, San Francisco, CA, 94111 <http://xa=
marin.com>

+1 (855) 926-2746 <http://xamarin.com>

Unsubscribe from all Xamarin emails at http://resources.xamarin.com/unsubsc=
ribe.html?mkt_unsubscribe=3D1&mkt_tok=3D3RkMMJWWfF9wsRonsq7KZKXonjHpfsX54u4=
lT%2Frn28M3109ad%2BrmPBy93oIAWp8na%2BqWCgseOrQ8mVsNV8q6RM0XrKw%3D.

------=_Part_-1536873954_1486546957.1401300129261
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head>
<meta name="generator" content="Say hello to Xamarin 3.">
<title>Say hello to Xamarin 3, which includes four major advances in mobile development.</title>
</head>
<body style="background-color:#F0F0F0; margin:0; padding:0; " ><div ><div class="mktEditable" ><center>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#F0F0F0">
<tbody>
<tr>
<td valign="middle" align="center" height="20" style="border-collapse: collapse;"></td>
</tr>
</tbody>
</table>
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="300" style="padding: 0px;"><a href=
"http://mkto-o0039.com/hd60L0O00J00005RQ040XTv" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/say-hello2.png" alt="Say hello to Xamarin 3, which includes four major advances in mobile development." width="600" height="300" style="border: none; outline: none;"></a></td>
</tr>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 10px 35px 0px;">Today we are very excited to announce Xamarin 3, which includes four major advances in mobile development:</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<!--Designer-->
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table width="600" height="70" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="70" style="padding: 20px 0px 0px;"><a href=
"http://mkto-o0039.com/E050J06UOMv0Q00X4R00d00" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/xamarin-designer-copy.png" alt="Xamarin Designer for iOS" width="600" height="70" style="border: none;"></a></td>
</tr>
</tbody>
</table>
<table width="600" height="310" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="310" style="padding: 0px;"><a href=
"http://mkto-o0039.com/MQ0X000vJR00500Vd06O0N4" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/ios-designer.png" height="310" width="600" alt="Xamarin Designer for iOS" style="border: none;"></a></td>
</tr>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 20px 50px 0px;">Xamarin is proud to unveil the world's best user interface designer for iOS, integrated into both Xamarin Studio and Visual Studio. Build beautiful native user interfaces, including live preview of custom controls, from the comfort of your favorite IDE. <a href=
"http://mkto-o0039.com/P000Q05JdO06O00R0vWX004" style="color: #3498db;text-decoration: none;outline: none;"
>Learn more &#187;</a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<!--Forms-->
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="70" style="padding: 40px 0px 0px;"><a href=
"http://mkto-o0039.com/z00v45d0000OQPR0J6X0X00" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/xamarin-forms-copy.png" alt="Meet Xamarin.Forms" width="600" height="70" style="border: none;"></a></td>
</tr>
</tbody>
</table>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="310" style="padding: 0px;"><a href=
"http://mkto-o0039.com/Y050R0YQ6000v004dOJ0QX0" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/forms.png" height="310" width="600" alt="Learn more about Xamarin.Forms" style="border: none;"></a></td>
</tr>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 20px 60px 0px;">Xamarin.Forms is a simple API that allows developers to quickly and easily build native iOS, Android and Windows Phone user interfaces from a single, shared C# codebase. Delivered as a portable class library, Xamarin.Forms includes more than 40 controls and layouts and makes it easy to mix and match your shared UI code with the native, platform-specific user interface capabilities Xamarin has always given you. <a href=
"http://mkto-o0039.com/K0000JO00dRR4Z5v600Q0X0" style="color: #3498db;text-decoration: none;outline: none;"
>Learn more &#187;</a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<!--Codesharing-->
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="70" style="padding: 40px 0px 0px;"><a href=
"http://mkto-o0039.com/R00d0v0O05004060JSXR0Q0" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/smooth-code-sharing.png" alt="Smooth Codesharing" width="600" height="70" style="border: none; outline: none;"></a></td>
</tr>
</tbody>
</table>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="255" style="padding: 0px;"><a href=
"http://mkto-o0039.com/WJ001QO0d0T4X560000vR00" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/smooth-codesharing.png" height="255" width="600" alt="Smooth Codesharing" style="border: none;"></a></td>
</tr>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 20px 60px 20px;">Xamarin 3 introduces Shared Projects and full support for Portable Class Libraries &#8212; two great new code-sharing techniques for cross-platform apps. <a href=
"http://mkto-o0039.com/p0000J002X000UQO5d06vR4" style="color: #3498db;text-decoration: none;outline: none;"
>Learn more &#187;</a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<!--Major IDE Enhancements-->
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="70" style="padding: 30px 0px 0px;"><a href=
"http://mkto-o0039.com/B0003J4XQ00000RO0vVd605" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/major-enhancements-copy.png" alt="Major IDE enhancements" width="600" height="70" style="border: none;"></a></td>
</tr>
</tbody>
</table>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="312" style="padding: 0px;"><a href=
"http://mkto-o0039.com/gW0v0Qd00400OX05J0004R6" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/xamarin-studio.png" height="312" width="600" alt="Check out the new Xamarin Studio" style="border: none;"></a></td>
</tr>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 20px 65px 20px;">Xamarin now includes a major user experience refresh, support for NuGet packages, full .NET BCL documentation, source analysis, F# support, streamlined Visual Studio support, and many other great features. <a href=
"http://mkto-o0039.com/F0vOd00X50J064R0000X5Q0" style="color: #3498db;text-decoration: none;outline: none;"
>Learn more &#187;</a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<!--And much more...-->
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td align="center" valign="center" height="70" style="padding: 10px 0px 0px;"><a href=
"http://mkto-o0039.com/I000YJv0d066Q5400R0OX00" style="text-align: center; display: block; text-decoration: none; outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/and-much-more-copy.png" alt="And much more..." width="600" height="70" style="border: none;"></a></td>
</tr>
</tbody>
</table>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#FFFFFF">
<tbody>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 5px 60px 20px;">These are just four of the hundreds of new features and enhancements in Xamarin 3. Please join us at one of <strong>two live webinars <a href=
"http://mkto-o0039.com/L004XO0000ZR0J7v60d050Q" style="color: #5C5C5C; text-decoration: none;"
>this Friday, May 30,</a></strong> where Xamarin co-founders Nat Friedman and Miguel de Icaza will present an overview of Xamarin 3. All webinar registrants will receive a copy of the recording, so please feel free to register even if you can't attend.</td>
</tr>
</tbody>
</table>
<table border="0" cellspacing="0" cellpadding="0" width="600" bgcolor="#FFFFFF" align="center">
<tbody>
<tr>
<td>
<table border="0" cellspacing="0" cellpadding="0" width="400" bgcolor="#FFFFFF" valign="center" align="center">
<tbody>
<tr>
<td cellpadding="0" cell-spacing="0" align="center" width="250">
<table>
<tbody>
<tr>
<td align="center" valign="center" height="45"><a href=
"http://mkto-o0039.com/m000Q94000050d6vOS00JX0" style="text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/register-for-5am.png" alt="Register for 5am PDT" width="181" height="35" style="border: none;"></a></td>
</tr>
</tbody>
</table>
</td>
<td cellpadding="0" cell-spacing="0" align="center" width="250">
<table>
<tbody>
<tr>
<td align="center" valign="center" height="45"><a href=
"http://mkto-o0039.com/G0O0XS40va01J05d00006Q0" style="text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/xamarin3/register-for-11am.png" alt="Register for 11am PDT" width="181" height="35" style="border: none;"></a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td valign="center" cellpadding="0" cell-spacing="0" align="center" style="border-collapse: collapse;color: #5C5C5C;font-family: Helvetica, Arial, sans-serif;font-size: 16px;margin: 0;text-align: center;font-weight: lighter;line-height: 165%;letter-spacing: 0; padding: 20px 40px 30px;">We've spent countless hours ensuring that Xamarin 3 is our best release yet, and we can't wait to show you what we've done.</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<!--Bottom addresses, logo-->
<table width="600" align="center" cellpadding="0" cellspacing="0" bgcolor="#F0F0F0">
<tbody>
<tr>
<td valign="middle" align="center" style="border-collapse:collapse; padding-top: 10px;">
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#F0F0F0">
<tbody>
<tr>
<td valign="middle" align="center" height="70" style="border-collapse: collapse;">
<table width="550" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#F0F0F0">
<tbody>
<tr>
<td valign="top" align="center" height="55" bgcolor="#F0F0F0" style="border-collapse: collapse;"><a href=
"http://mkto-o0039.com/v00v0QS205dXJ6b0O040000" target="_blank" style="color: #bbbbbb;text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/trial/grey-xamarin.png" style="display: block;" alt="Visit" border="0" align="top" hspace="0" vspace="0" width="55" height="55"></a></td>
<td valign="top" align="center" height="55" bgcolor="#F0F0F0" style="border-collapse: collapse;"><a href=
"http://mkto-o0039.com/HJ004000Q6cvSX00d0O0035" target="_blank" style="color: #bbbbbb;text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/trial/grey-blog.png" style="display: block;" alt="Blog" border="0" align="top" hspace="0" vspace="0" width="55" height="55"></a></td>
<td valign="top" align="center" height="55" bgcolor="#F0F0F0" style="border-collapse: collapse;"><a href=
"http://mkto-o0039.com/v00v0QS405dXJ6d0O040000" target="_blank" style="color: #bbbbbb;text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/trial/grey-linkedin.png" style="display:block;" alt="Link" border="0" align="top" hspace="0" vspace="0" width="55" height="55"></a></td>
<td valign="top" align="center" height="55" bgcolor="#F0F0F0" style="border-collapse: collapse;"><a href=
"http://mkto-o0039.com/G0O0XS40ve05J05d00006Q0" target="_blank" style="color: #bbbbbb;text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/trial/grey-facebook.png" style="display:block;" alt="Friend" border="0" align="top" hspace="0" vspace="0" width="55" height="55"></a></td>
<td valign="top" align="center" height="55" bgcolor="#F0F0F0" style="border-collapse: collapse;"><a href=
"http://mkto-o0039.com/p0000J00fX0006QO5d06vS4" target="_blank" style="color: #bbbbbb;text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/trial/grey-google-plus.png" style="display: block;" alt="G+" border="0" align="top" hspace="0" vspace="0" width="55" height="55"></a></td>
<td valign="top" align="center" height="55" bgcolor="#F0F0F0" style="border-collapse: collapse;"><a href=
"http://mkto-o0039.com/ZOQ0600g5000000v740dXJS" target="_blank" style="color: #bbbbbb;text-decoration: none;outline: none;"
><img src="http://cdn1.xamarin.com/webimages/images/email/trial/grey-twitter.png" style="display:block;" alt="Tweet" border="0" align="top" hspace="0" vspace="0" width="55" height="55"></a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<table width="600" align="center" cellpadding="0" cellspacing="0" bgcolor="#F0F0F0">
<tbody>
<tr>
<td style="padding: 0px; color: #5C5C5C; font-weight: lighter; font-family: Helvetica, Arial, sans-serif; font-size: 12px; line-height: 165%; vertical-align: top; text-align: center;"><span><a href=
"http://mkto-o0039.com/Y050S0hQ6000v004dOJ08X0" style="color: #5C5C5C;text-decoration: none;outline: none;"
>&nbsp;&nbsp;394 Pacific Ave. 4th Floor, San Francisco, CA, 94111</a><br>
<a href=
"http://mkto-o0039.com/Y050S0hQ6000v004dOJ08X0" style="color: #5C5C5C;text-decoration: none;outline: none;"
>+1 (855) 926-2746</a><br></span></td>
</tr>
</tbody>
</table>
<table width="600" align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#F0F0F0">
<tbody>
<tr>
<td valign="middle" align="center" height="20" style="border-collapse: collapse;"></td>
</tr>
</tbody>
</table>
</center>
</div>
</div>

<IMG SRC="http://mkto-o0039.com/trk?t=1&mid=OTc1LUpPWC03Njk6MjI5MToxOTIzOjQxNjY6MjoyNjExOjc6MTkyODpqZWZmQHhhbWFyaW4uY29t" WIDTH="1" HEIGHT="1" BORDER="0" ALT="" />

</body>
</html>
------=_Part_-1536873954_1486546957.1401300129261--
