//
// CappedComplianceLogger.cs
//
// Author: Jeffrey Stedfast <jestedfa@microsoft.com>
//
// Copyright (c) 2013-2026 .NET Foundation and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

using System;

namespace MimeKit {
	/// <summary>
	/// A compliance logger that limits how many times each violation may be reported.
	/// </summary>
	/// <remarks>
	/// <para>The number of issues a message can produce is bounded only by its size, and the densest
	/// forms cost an attacker only a few bytes per issue, so an untrusted message can be made to
	/// produce issues far faster than anything downstream can afford to record them.</para>
	/// <para>The budget is per violation rather than a single total deliberately. A total budget is
	/// itself an attack: a message can open with a flood of cheap, harmless violations and place the
	/// interesting ones after the point where the budget is known to run out. Giving each violation
	/// its own budget means that no violation can crowd out any other, and the overall number of
	/// issues is still bounded, at the number of distinct violations times the limit.</para>
	/// </remarks>
	sealed class CappedComplianceLogger : IMimeComplianceLogger
	{
		// Note: One counter per violation. The enum is a small, dense, zero-based range, so this is a
		// flat array indexed by the violation rather than a dictionary.
		readonly int[] counts;
		readonly IMimeComplianceLogger logger;
		readonly int limit;
		bool reportedTruncation;

		/// <summary>
		/// Initialize a new instance of the <see cref="CappedComplianceLogger"/> class.
		/// </summary>
		/// <remarks>
		/// Creates a new capped compliance logger.
		/// </remarks>
		/// <param name="logger">The logger to forward issues to.</param>
		/// <param name="limit">The maximum number of times that each violation may be reported.</param>
		public CappedComplianceLogger (IMimeComplianceLogger logger, int limit)
		{
			// Note: TooManyComplianceIssues is deliberately left out of the array. It is not a defect
			// in the message and is generated by this class rather than by a validator, so it is never
			// counted against a budget and never suppressed. It sits outside the contiguous range of
			// defects, so it falls into the pass-through branch of Log() on its own.
			this.counts = new int[(int) MimeComplianceViolation.IncompleteUUEncodedContent + 1];
			this.logger = logger;
			this.limit = limit;
		}

		/// <summary>
		/// Get the logger that issues are forwarded to.
		/// </summary>
		/// <remarks>
		/// Gets the logger that issues are forwarded to.
		/// </remarks>
		/// <value>The inner logger.</value>
		public IMimeComplianceLogger InnerLogger {
			get { return logger; }
		}

		/// <summary>
		/// Reset the budget.
		/// </summary>
		/// <remarks>
		/// Resets the budget so that every violation may be reported afresh. This is called at the
		/// start of each parse operation so that the limit applies per message rather than for the
		/// lifetime of the reader, which would otherwise starve every message after the first when a
		/// single reader is used to walk something like an mbox.
		/// </remarks>
		public void Reset ()
		{
			Array.Clear (counts, 0, counts.Length);
			reportedTruncation = false;
		}

		/// <summary>
		/// Log a MIME compliance violation.
		/// </summary>
		/// <remarks>
		/// Forwards the issue to the inner logger unless the violation has already been reported
		/// <see cref="MimeReader.MaxComplianceIssuesPerViolation"/> times.
		/// </remarks>
		/// <param name="issue">The MIME compliance issue that was detected.</param>
		public void Log (in MimeComplianceIssue issue)
		{
			int index = (int) issue.Violation;

			if ((uint) index >= (uint) counts.Length) {
				logger.Log (issue);
				return;
			}

			if (counts[index] < limit) {
				counts[index]++;
				logger.Log (issue);
				return;
			}

			// Note: The report is incomplete from the first suppressed issue onward, so the marker is
			// emitted there and not repeated. Repeating it for every violation that later reaches its
			// own limit would reintroduce, in miniature, the flooding this class exists to prevent.
			if (!reportedTruncation) {
				reportedTruncation = true;

				logger.Log (new MimeComplianceIssue (issue.Context, MimeComplianceViolation.TooManyComplianceIssues, issue.StreamOffset, issue.LineNumber, issue.ColumnNumber));
			}
		}
	}
}
